export const PENDING_DATA = [
  {
    User: "Sam Altman",
    Email: "samaltman123@gmail.com",
    "Risk level": "2",
    "Trigger Reason": "IP Change",
    "In queue for": "4",
    "Date added on": "12 Oct,2023",
    "Previously reviewed": true,
    PRD: "23 Aug,2023",
  },
  {
    User: "Sameer Choubey",
    Email: "sameerchoubey123@gmail.com",
    "Risk level": "1",
    "Trigger Reason": "FIFO",
    "In queue for": "4",
    "Date added on": "12 Oct,2023",
    "Previously reviewed": false,
  },
  {
    User: "Adarsh Pannikar",
    Email: "adarsh@ojuno.com",
    "Risk level": "3",
    "Trigger Reason": "IP Change",
    "In queue for": "5",
    "Date added on": "12 Oct,2023",
    "Previously reviewed": false,
  },
  {
    User: "Pratik Shetty",
    Email: "pratik3@gmail.com",
    "Risk level": "1",
    "Trigger Reason": "FIFO",
    "In queue for": "5",
    "Date added on": "12 Oct,2023",
    "Previously reviewed": true,
    PRD: "12 Sep,2023",
  },
  {
    User: "Elon Musk",
    Email: "elon@twitterceo.com",
    "Risk level": "3",
    "Trigger Reason": "FIFO",
    "In queue for": "5",
    "Date added on": "12 Oct,2023",
    "Previously reviewed": true,
    PRD: "12 Sep,2023",
  },
  {
    User: "Trina Kundu",
    Email: "trina@onjuno.com",
    "Risk level": "3",
    "Trigger Reason": "FIFO",
    "In queue for": "5",
    "Date added on": "12 Oct,2023",
    "Previously reviewed": true,
    PRD: "12 Sep,2023",
  },
];
export const COMPLETED_DATA = [
  {
    User: "Sam Altman",
    Email: "samaltman123@gmail.com",
    "Risk level": "2",
    "Action Reason": "Flagged",
    "Time to close": "14",
    "Date added on": "12 Oct,2023",
    "Action taken by": "Neil",
    Email2: "neil@onjuno.com",
  },
  {
    User: "Sameer Choubey",
    Email: "sameerchoubey123@gmail.com",
    "Risk level": "1",
    "Action Reason": "Closed",
    "Time to close": "14",
    "Date added on": "12 Oct,2023",
    "Action taken by": "Pratik",
    Email2: "pratik@onjuno.com",
  },
  {
    User: "Adarsh Pannikar",
    Email: "adarsh@ojuno.com",
    "Risk level": "3",
    "Action Reason": "Cleared",
    "Time to close": "15 ",
    "Date added on": "12 Oct,2023",
    "Action taken by": "Prashanth",
    Email2: "prashanth@onjuno.com",
  },
  {
    User: "Pratik Shetty",
    Email: "pratik3@gmail.com",
    "Risk level": "1",
    "Action Reason": "SOI requested",
    "Time to close": "15 ",
    "Date added on": "12 Oct,2023",
    "Action taken by": "Rasleen Kaur",
    Email2: "rasleen@onjuno.com",
  },
  {
    User: "Elon Musk",
    Email: "elon@twitterceo.com",
    "Risk level": "3",
    "Action Reason": "Flagged",
    "Time to close": "15 ",
    "Date added on": "12 Oct,2023",
    "Action taken by": "Pratik Shetty",
    Email2: "pratik@onjuno.com",
  },
  {
    User: "Trina Kundu",
    Email: "trina@onjuno.com",
    "Risk level": "3",
    "Action Reason": "Closed",
    "Time to close": "15 ",
    "Date added on": "12 Oct,2023",
    "Action taken by": "Varun Deshpande",
    Email2: "varun@onjuno.com",
  },
];
